### ISSUE TITLE
No links in readme. 

### ISSUE THREAD

**Issue by yauhenl** [tlefko/Matebook-X-Pro-2018-Ventura#29]
Could you please update installation guide with working links?
Also not really understand how to create bootable USB with installer from Windows or Linux OS

**Comment by yauhenl** [comment]
@tlefko  But I don't have macOS. Because that I want to install hackintoch. Anyway I installed it already used several sources from internet. It took several hours for me and will be useful have some guide in one place.

**Comment by tlefko** [comment]
@yauhenl Okay, I see where you're coming from. So were you able to get everything up and working? Walk me through how you created the installation media on windows and we can merge it into readme. I'll credit you as well.

**Comment by yauhenl-io** [comment]
@tlefko Yes. Everything works fine. I used [gibMacOS](https://github.com/corpnewt/gibMacOS) to create installer from Windws. Also I had to modify config to enable wifi in Catalina. After that I just updated macos to Monterey used default updater

**Comment by rohirrim27** [comment]
HI @yauhenl  or @tlefko, could you advise on how exactly to modify config.plist to enable WiFi on Catalina? I just completed a fresh install today but stuck with no WiFi.

I've tried:

- On Windows: downloading AirportItlwm v2.1.0 stable Catalina.kext and replacing the AirportItlwm.kext in EFI/OC/Kexts with it. I updated SecureBootModel to Default in config.plist using ProperTree (or notepad) but I get the following schema errors on boot: 
![IMG_1574](https://user-images.githubusercontent.com/75772430/209421164-a8ef4750-35a9-48c5-9a3a-3f210ccd536c.jpg)

- On MacOs: I used OpenCore Configurator to do the same but still running into schema errors on reboot.

Appreciate any help here! Also since I'm fresh off doing an install, I can help write out an in-depth installation guide once I've resolved all these issues.

**Comment by tlefko** [comment]
so I believe the issue here might be the version of OC configurator used as
its probably corrupting the plist file as I’m not sure what version you’re
using for the release but the OC version of the config is older. I would
try changing the secure boot model with a text editor, also with catalina
there is also a way to do the wifi thru an IO802.11kext. For now, try this
text edit approach.

**Comment by rohirrim27** [comment]
Thanks for the super fast response! I'm using the EFI from the latest release - MBXP Ventura 1.1.1

I tried editing it using multiple tools - ProperTree, OC Configurator, Notepad but it keeps getting corrupted. To confirm, the steps are:
1. Replace AirportItlwm.kext in the kext folder with the latest Catalina version of the kext but renamed to be the same.
2. Update plist using text editor to set secure boot model to default. No other changes to plist required?

I'll give it a shot and report back but in case it doesn't work, will create a new issue to get help from someone who may have recently solved this problem!

**Comment by rohirrim27** [comment]
Didn't work unfortunately. Any attempt to edit the plist breaks booting, even if I use text editor.

**Comment by tlefko** [comment]
Would suggest that you downgrade to the earlier versions and then try
again, Ventura version changed a lot of stuff

**Comment by rohirrim27** [comment]
Yep, finally got WiFi working by using the EFI from Monterey 1.2 release! 

Ventura working beautifully, thank you for the hard work on keeping this up to date! I'm keen to help write out a installation guide for others embarking on this process - will follow up soon.

**Comment by tlefko** [comment]
Oh that would be amazing if you could do that, I know it’s what’s on the
docs right now is incredibly messy just been super busy with school. Also,
look at the track pad issue and let me know if you’ve any thoughts as to
why that may be happening for some people

**Comment by tlefko** [comment]
Fantastic to hear that everything’s working now, how is the performance and
all that
